<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.bonitasoft.custompage</groupId>
	<artifactId>bonita-truckmilk</artifactId>
	<!-- Attention, when number change here, update -->
	<!-- * MilkCmdControlAPI.BONITA_TRUCKMILK_VERSION  -->

	<version>2.9.0</version>
	<properties>
		<bonita.version>7.8.4</bonita.version>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<sonar.sources>pom.xml,src</sonar.sources>
		<sonar.java.binaries>target/classes</sonar.java.binaries>

	</properties>
	<name>TruckMilk</name>
	<dependencies>


		<dependency>
			<groupId>org.bonitasoft.engine</groupId>
			<artifactId>bonita-client</artifactId>
			<version>${bonita.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.bonitasoft.engine</groupId>
			<artifactId>bonita-server</artifactId>
			<version>${bonita.version}</version>
			<scope>provided</scope>
		</dependency>

		<!-- Change here ? report the modification in MilkCmdControlAPI.getMilkCommandDescription() -->
		<dependency>
			<groupId>org.bonitasoft.log.event</groupId>
			<artifactId>bonita-event</artifactId>
			<version>1.10.0</version>
		</dependency>
		<!-- Change here ? report the modification in MilkCmdControlAPI.getMilkCommandDescription() -->
		<dependency>
			<groupId>org.bonitasoft.properties</groupId>
			<artifactId>bonita-properties</artifactId>
			<version>2.8.3</version>
		</dependency>
		<dependency>
			<groupId>org.bonitasoft.tools</groupId>
			<artifactId>bonita-casedetails</artifactId>
			<version>1.1.2</version>
		</dependency>
		<dependency>
			<groupId>org.bonitasoft.custompage</groupId>
			<artifactId>bonita-meteor</artifactId>
			<version>4.0.0</version>
		</dependency>
		<!-- Change here ? report the modification in MilkCmdControlAPI.getMilkCommandDescription() -->
		<dependency>
			<groupId>org.bonitasoft.custompage</groupId>
			<artifactId>bonita-sonar</artifactId>
			<version>1.1.0</version>
		</dependency>
		<!--  we have to register explicitaly the codenarc to have it in the dependency and copy it to the command -->
		<dependency>
			<groupId>org.codenarc</groupId>
			<artifactId>CodeNarc</artifactId>
			<version>1.6.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.bonitasoft.custompage</groupId>
			<artifactId>bonita-worker</artifactId>
			<version>1.9.0</version>
		</dependency>
		<dependency>
			<groupId>org.bonitasoft.custompage</groupId>
			<artifactId>bonita-grumman</artifactId>
			<version>1.2.0</version>
		</dependency>
		<dependency>
			<groupId>org.bonitasoft.custompage</groupId>
			<artifactId>bonita-log</artifactId>
			<version>2.6.1</version>
		</dependency>
		<dependency>
			<groupId>org.bonitasoft.custompage</groupId>
			<artifactId>bonita-explorer</artifactId>
			<version>1.0.0</version>
		</dependency>
		
		
		<dependency>
			<groupId>org.bonitasoft.command</groupId>
			<artifactId>bonita-commanddeployment</artifactId>
			<version>2.1.3</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.26</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.5.0-b01</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/javax.activation/activation -->
		<dependency>
		    <groupId>javax.activation</groupId>
		    <artifactId>activation</artifactId>
		    <version>1.1.1</version>
		</dependency>


		<!-- to execute the Deploy Plugin -->
		<dependency>
			<groupId>org.bonitasoft.store</groupId>
			<artifactId>bonita-store</artifactId>
			<version>2.8.0</version>
		</dependency>

	</dependencies>


	<!-- ******************** Community Maven repository **************** -->
	<repositories>
		<repository>
			<releases>
				<enabled>true</enabled>
				<checksumPolicy>warn</checksumPolicy>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>logPageBonita</id>
			<name>logPageBonita</name>
			<url>https://raw.githubusercontent.com/Bonitasoft-Community/bonitamavenrepository/master</url>
			<layout>default</layout>
		</repository>
	</repositories>

	<build>
		<!-- ******************** Sonar **************** -->
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.8.1</version>
				</plugin>
				<plugin>
					<groupId>org.sonarsource.scanner.maven</groupId>
					<artifactId>sonar-maven-plugin</artifactId>
					<version>3.6.0.1398</version>
				</plugin>
				<plugin>
					<groupId>org.jacoco</groupId>
					<artifactId>jacoco-maven-plugin</artifactId>
					<version>0.8.4</version>
				</plugin>
			</plugins>
		</pluginManagement>


		<plugins>

			<!-- ******************** Generate the Quartz Jar File **************** -->
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<executions>
					<execution>
						<id>only-library</id>
						<goals>
							<goal>jar</goal>
						</goals>
						<phase>package</phase>
						<configuration>
							<classifier>Page</classifier>
							<excludes>
								<exclude>org/bonitasoft/truckmilk/schedule/quartz/*</exclude>
							</excludes>
						</configuration>
					</execution>

					<execution>
						<id>everything</id>
						<goals>
							<goal>jar</goal>
						</goals>
						<phase>package</phase>
						<configuration>
							<classifier>Quartzjob</classifier>
							<includes>
								<include>org/bonitasoft/truckmilk/schedule/quartz/*</include>
							</includes>
						</configuration>
					</execution>
				</executions>
			</plugin>


			<!-- ******************** Copy JAR files under lib **************** -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.1.1</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>${basedir}/lib</outputDirectory>
							<overWriteReleases>true</overWriteReleases>
							<overWriteSnapshots>true</overWriteSnapshots>
							<excludeTransitive>true</excludeTransitive>
							<excludeScope>provided</excludeScope>
						</configuration>
					</execution>

					<!-- <execution> <id>copy-Jar</id> <phase>package</phase> <goals> <goal>copy</goal> </goals> <configuration> <outputDirectory>${basedir}/lib</outputDirectory> <artifactItems> <artifactItem> <groupId>${project.groupId}</groupId> 
						<artifactId>${project.artifactId}</artifactId> <version>${project.version}</version> <overWrite>true</overWrite> </artifactItem> </artifactItems> <resources> <resource> <directory>target</directory> <includes> 
						<include>*-Page.jar</include> <include>*-Quartzjob.jar</include> </includes> </resource> </resources> </configuration> </execution> -->
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.1.0</version>
				<executions>
					<execution>
						<id>copy-Specific-Jar-Page</id>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${basedir}/lib</outputDirectory>
							<resources>
								<resource>
									<directory>target</directory>
									<includes>
										<include>*-Page.jar</include>
									</includes>
								</resource>
							</resources>

						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.1.0</version>
				<executions>
					<execution>
						<id>copy-Specific-Jar-Quartz</id>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${basedir}/additionallib</outputDirectory>
							<resources>
								<resource>
									<directory>target</directory>
									<includes>
										<include>*-Quartzjob.jar</include>
									</includes>
								</resource>
							</resources>

						</configuration>
					</execution>
				</executions>
			</plugin>
			<!-- ******************** Generate the Resource (ZIP FILE) -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.1.1</version>
				<executions>

					<execution>
						<id>build-bonitaresource</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<inherited>false</inherited>
						<configuration>
							<finalName>${project.artifactId}-${project.version}</finalName>
							<ignoreDirFormatExtensions>true</ignoreDirFormatExtensions>
							<appendAssemblyId>false</appendAssemblyId>
							<descriptors>
								<descriptor>src/assembly/buildzip.xml</descriptor>
							</descriptors>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<!-- *************** deploy the resource localy -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.1.1</version>

				<executions>
					<execution>
						<id>Deploy Page to Bonita Server</id>

						<phase>install</phase>
						<goals>
							<goal>java</goal>
						</goals>
						<configuration>
							<mainClass>org.bonitasoft.store.BonitaStoreAccessorClient</mainClass>
							<arguments>
								<argument>http://localhost:8080</argument>
								<argument>bonita</argument>
								<argument>Walter.Bates</argument>
								<argument>bpm</argument>
								<argument>target/${project.artifactId}-${project.version}.zip</argument>
								<!-- use UPDATE or DELETEANDADD -->
								<argument>strategy:UPDATE</argument>
								<argument>profile:BOTools</argument>
							</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>



		</plugins>
	</build>


</project>
